# Generated by Django 4.2.3 on 2023-07-16 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('home_phone_number', models.CharField(max_length=20, unique=True)),
                ('home_address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office_phone_number', models.CharField(max_length=20, null=True)),
                ('nationality', models.CharField(max_length=30, null=True)),
                ('marital_status', models.CharField(max_length=20, null=True)),
                ('age', models.CharField(max_length=30)),
                ('nin', models.CharField(max_length=30, unique=True)),
                ('office_address', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=30)),
                ('photo', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Patients',
            },
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('home_phone_number', models.CharField(max_length=20, unique=True)),
                ('home_address', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='post.patient')),
                ('relationship', models.CharField(max_length=50)),
                ('photo', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Emergency contact information',
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('patient', models.ManyToManyField(to='post.patient')),
            ],
            options={
                'db_table': 'Allergies',
            },
        ),
    ]
